Spring:
  datasource:
    username: root
    password: neoware
    url: jdbc:mysql://localhost:3306/music
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: student-service
server:
  port: 8012
logging:
  file: log\info.log